spring.application.name=url-shortener

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/url-shortener-db
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Show SQL queries in the console logs
spring.jpa.show-sql=true